// src/constants/tools.js — single source of truth for all tool metadata

export const TOOLS = [
  {
    key:         'merge',
    icon:        '🔗',
    title:       'Merge PDF',
    desc:        'Combine multiple PDFs into one. Drag to reorder, then merge instantly.',
    path:        '/merge-pdf',
    color:       '#2563EB',
    driveFolder: 'Merged',
  },
  {
    key:         'split',
    icon:        '✂️',
    title:       'Split PDF',
    desc:        'Extract page ranges or split every page into individual PDFs.',
    path:        '/split-pdf',
    color:       '#7C3AED',
    driveFolder: 'Split',
  },
  {
    key:         'image_to_pdf',
    icon:        '🧩',
    title:       'Image to PDF',
    desc:        'Turn JPG, PNG, or WebP images into a single PDF — fast and private.',
    path:        '/image-to-pdf',
    color:       '#F97316',
    driveFolder: 'Images',
  },
  {
    key:         'organize',
    icon:        '🗂️',
    title:       'Organize PDF',
    desc:        'Reorder and delete pages in a PDF, then export a clean copy.',
    path:        '/organize-pdf',
    color:       '#06B6D4',
    driveFolder: 'Organized',
  },
  {
    key:         'watermark',
    icon:        '💧',
    title:       'Watermark PDF',
    desc:        'Add text or image watermarks to every page instantly.',
    path:        '/watermark-pdf',
    color:       '#0EA5E9',
    driveFolder: 'Watermarked',
  },
  {
    key:         'crop',
    icon:        '✂️',
    title:       'Crop PDF',
    desc:        'Trim margins on every page with precise controls.',
    path:        '/crop-pdf',
    color:       '#F59E0B',
    driveFolder: 'Cropped',
  },
  {
    key:         'compress',
    icon:        '⚡',
    title:       'Compress PDF',
    desc:        'Reduce file size without losing quality. Perfect for email and sharing.',
    path:        '/compress-pdf',
    color:       '#0EA5E9',
    driveFolder: 'Compressed',
  },
  {
    key:         'convert',
    icon:        '🖼️',
    title:       'PDF to JPG',
    desc:        'Convert every page to a high-quality JPG image — right in your browser.',
    path:        '/convert-pdf',
    color:       '#10B981',
    driveFolder: 'Converted',
  },
  {
    key:         'rotate',
    icon:        '🔄',
    title:       'Rotate PDF',
    desc:        'Rotate all pages by 90°, 180° or 270° — done in seconds.',
    path:        '/rotate-pdf',
    color:       '#EC4899',
    driveFolder: 'Rotated',
  },
  {
    key:         'pagenums',
    icon:        '🔢',
    title:       'Page Numbers',
    desc:        'Stamp clean page numbers onto any PDF. Choose position and style.',
    path:        '/page-numbers',
    color:       '#F59E0B',
    driveFolder: 'Page Numbers',
  },
];
