// src/constants/tools.js — single source of truth for all tool metadata

export const CATEGORIES = {
  CONVERT:  'Convert & Compress',
  ORGANIZE: 'Organize',
  EDIT:     'View & Edit',
  SECURITY: 'Security & Meta',
};

export const TOOLS = [
  {
    key:         'merge',
    category:    CATEGORIES.ORGANIZE,
    icon:        '📂',
    title:       'Merge PDF',
    desc:        'Combine multiple PDFs into one document easily.',
    path:        '/merge-pdf',
    color:       '#4F46E5',
    driveFolder: 'Merged',
  },
  {
    key:         'split',
    category:    CATEGORIES.ORGANIZE,
    icon:        '✂️',
    title:       'Split PDF',
    desc:        'Separate one page or a whole range for easy use.',
    path:        '/split-pdf',
    color:       '#10B981',
    driveFolder: 'Split',
  },
  {
    key:         'compress',
    category:    CATEGORIES.CONVERT,
    icon:        '📉',
    title:       'Compress PDF',
    desc:        'Reduce file size while keeping high quality.',
    path:        '/compress-pdf',
    color:       '#EF4444',
    driveFolder: 'Compressed',
  },
  {
    key:         'rotate',
    category:    CATEGORIES.ORGANIZE,
    icon:        '🔄',
    title:       'Rotate PDF',
    desc:        'Rotate your PDF pages to perfection.',
    path:        '/rotate-pdf',
    color:       '#F59E0B',
    driveFolder: 'Rotated',
  },
  {
    key:         'convert',
    category:    CATEGORIES.CONVERT,
    icon:        '🔄',
    title:       'PDF Converter',
    desc:        'Convert PDFs to images or images to PDF.',
    path:        '/convert-pdf',
    color:       '#8B5CF6',
    driveFolder: 'Converted',
  },
  {
    key:         'image_to_pdf',
    category:    CATEGORIES.CONVERT,
    icon:        '🖼️',
    title:       'Image to PDF',
    desc:        'Turn your images into a professional PDF.',
    path:        '/image-to-pdf',
    color:       '#EC4899',
    driveFolder: 'ImagesToPdf',
  },
  {
    key:         'organize',
    category:    CATEGORIES.ORGANIZE,
    icon:        '📑',
    title:       'Organize PDF',
    desc:        'Rearrange, delete or add pages in your PDF.',
    path:        '/organize-pdf',
    color:       '#0EA5E9',
    driveFolder: 'Organized',
  },
  {
    key:         'watermark',
    category:    CATEGORIES.EDIT,
    icon:        '🏷️',
    title:       'Watermark PDF',
    desc:        'Add text or image watermarks to your documents.',
    path:        '/watermark-pdf',
    color:       '#6366F1',
    driveFolder: 'Watermarked',
  },
  {
    key:         'crop',
    category:    CATEGORIES.ORGANIZE,
    icon:        '📐',
    title:       'Crop PDF',
    desc:        'Crop PDF margins and adjust page size.',
    path:        '/crop-pdf',
    color:       '#14B8A6',
    driveFolder: 'Cropped',
  },
  {
    key:         'page_numbers',
    category:    CATEGORIES.EDIT,
    icon:        '🔢',
    title:       'Page Numbers',
    desc:        'Add page numbers to your PDF with ease.',
    path:        '/page-numbers',
    color:       '#F97316',
    driveFolder: 'Page Numbers',
  },
  {
    key:         'metadata',
    category:    CATEGORIES.SECURITY,
    icon:        '📝',
    title:       'Metadata Editor',
    desc:        'View and edit PDF properties like Title, Author, and Keywords.',
    path:        '/metadata-editor',
    color:       '#10B981',
    driveFolder: 'Metadata',
  },
  {
    key:         'text_extract',
    category:    CATEGORIES.CONVERT,
    icon:        '🔍',
    title:       'PDF to Text',
    desc:        'Extract all text content from a PDF file instantly.',
    path:        '/pdf-to-text',
    color:       '#6366F1',
    driveFolder: 'Extracted Text',
  },
  {
    key:         'protect',
    category:    CATEGORIES.SECURITY,
    icon:        '🛡️',
    title:       'Protect PDF',
    desc:        'Secure PDFs with military-grade AES-256 encryption.',
    path:        '/protect-pdf',
    color:       '#6366F1',
    driveFolder: 'Protected',
  },
  {
    key:         'unlock',
    category:    CATEGORIES.SECURITY,
    icon:        '🔓',
    title:       'Unlock PDF',
    desc:        'Decrypt and remove password protection from your PDFs.',
    path:        '/unlock-pdf',
    color:       '#10B981',
    driveFolder: 'Unlocked',
  },
  {
    key:         'permissions',
    category:    CATEGORIES.SECURITY,
    icon:        '🔐',
    title:       'PDF Permissions',
    desc:        'Control printing, copying, and editing restrictions.',
    path:        '/pdf-permissions',
    color:       '#F59E0B',
    driveFolder: 'Secured',
  },
];
